config/routes.rb
Masterit::Application.routes.draw do


  devise_scope :expert do
    post "users/omniauth_callbacks", to: "users/omniauth_callbacks#registration"
  end

  devise_scope :participant do
    post "users/omniauth_callbacks", to: "users/omniauth_callbacks#registration"
  end

  devise_scope :moderator do
    post "users/omniauth_callbacks", to: "users/omniauth_callbacks#registration"
  end

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => 'users/registrations' }

  devise_scope :admin do
    post "users/omniauth_callbacks", :to => "users/omniauth_callbacks#registration"
  end

  mount RailsAdmin::Engine => '/admin/rails_admin', :as => 'rails_admin'

  #root :to => "web/welcome#index"

  scope :module => :web do
    root :to => 'welcome#index'

    namespace :expert do
      root to: "welcome#index"
      resources :works, only: [:index, :show] do
        member do
          put :remove_from_basket
          put :trigger_estimate
        end
      end
      resources :estimations, only: [:edit, :update]
      resources :work_nominations, only: [:index]
    end
    namespace :moderator do
      root to: "welcome#index"
      resources :works, only: [:index, :show] do
        member do
          put :trigger_plagiat
        end
      end
      resources :users, only: [:index]
      resources :plagiat_details, only: [:index]
      resources :experts, only: [:index, :show] do
        scope module: :experts do
          resources :works, only: [:index, :show] do
            member do
              put :set_works_to_expert
              put :remove_works_from_expert
            end
          end
          resources :nominations, only: [:index, :show] do
            member do
              put :set_nomination_to_expert
              put :remove_nomination_from_expert
            end
          end
        end
      end
    end

    namespace :admin do
      root to: "welcome#index"
      resources :work_nominations
      resources :works
      resources :regions
      resources :competitions
      resources :tours
      resources :users, only: [:index, :edit, :update]
      resources :moderators, only: [:index, :show]
      resources :experts, only: [:index, :show] do
        scope module: :experts do
          resources :works, only: [:index, :show] do
            member do
              put :set_works_to_expert
              put :remove_works_from_expert
            end
          end
          resources :nominations, only: [:index, :show] do
            member do
              put :set_nomination_to_expert
              put :remove_nomination_from_expert
            end
          end
        end
      end
      resources :moderators, only: [:index, :show] do
        scope module: :moderators do
          resources :regions, only: [:index, :show] do
            member do
              put :set_region_to_moderator
              put :remove_region_from_moderator
            end
          end
        end
      end
      resource :expert do 
        member do
          put :send_invite_to_expert
        end
      end
      resource :moderator do 
        member do
          put :send_invite_to_moderator
        end
      end
      resource :user, only: [] do
        member do
          put :invite_to_expert
          put :invite_to_moderator
        end
      end
      resources :menu_items do
        scope module: :menu_items do
          resources :pages
        end
      end
    end

    resources :competitions, only: [:index, :show] do
      scope module: :competitions do
        resources :work_nominations, only: [:index, :show] do
          resource :plagiat_details, only: [:destroy, :new, :create, :edit, :update]
        end
      end
    end
    resources :pages, only: [:show]
    resources :users, only: [:show, :edit, :update]
    resources :works
    resources :comments
  end
end

app/models/registration_work.rb
class RegistrationWork < ActiveRecord::Base
  attr_accessible :area, :city, :name_class, :description, :supervizor, :partners, :email, :name, :nominate, :phone, :picture, :school, :url_work
end

app/controllers/registration_works_controller.rb
class RegistrationWorksController < ApplicationController
  # GET /registration_works
  # GET /registration_works.json
  def index
    @registration_works = RegistrationWork.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @registration_works }
    end
  end

  # GET /registration_works/1
  # GET /registration_works/1.json
  def show
    @registration_work = RegistrationWork.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @registration_work }
    end
  end

  # GET /registration_works/new
  # GET /registration_works/new.json
  def new
    @registration_work = RegistrationWork.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @registration_work }
    end
  end

  # GET /registration_works/1/edit
  def edit
    @registration_work = RegistrationWork.find(params[:id])
  end

  # POST /registration_works
  # POST /registration_works.json
  def create
    @registration_work = RegistrationWork.new(params[:registration_work])

    respond_to do |format|
      if @registration_work.save
        format.html { redirect_to @registration_work, notice: 'Registration work was successfully created.' }
        format.json { render json: @registration_work, status: :created, location: @registration_work }
      else
        format.html { render action: "new" }
        format.json { render json: @registration_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /registration_works/1
  # PUT /registration_works/1.json
  def update
    @registration_work = RegistrationWork.find(params[:id])

    respond_to do |format|
      if @registration_work.update_attributes(params[:registration_work])
        format.html { redirect_to @registration_work, notice: 'Registration work was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @registration_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registration_works/1
  # DELETE /registration_works/1.json
  def destroy
    @registration_work = RegistrationWork.find(params[:id])
    @registration_work.destroy

    respond_to do |format|
      format.html { redirect_to registration_works_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/registration_works_helper.rb
module RegistrationWorksHelper
end

app/views/registration_works/_form.html.haml
= simple_form_for(@registration_work) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :nominate
    = f.input :picture
    = f.input :description
    = f.input :supervizor
    = f.input :partners
    = f.input :city
    = f.input :school
    = f.input :area
    = f.input :name_class
    = f.input :url_work
    = f.input :email
    = f.input :phone

  .form-actions
    = f.button :submit

app/views/registration_works/edit.html.haml
%h1 Editing registration_work

= render 'form'

= link_to 'Show', @registration_work
\|
= link_to 'Back', registration_works_path

app/views/registration_works/index.html.haml
%h1 Listing registration_works

%table
  %tr
    %th Name
    %th Nominate
    %th Picture
    %th Description
    %th Supervizor
    %th Partners
    %th City
    %th School
    %th Area
    %th Name class
    %th Url work
    %th Email
    %th Phone
    %th 
    %th
    %th

  - @registration_works.each do |registration_work|
    %tr
      %td= registration_work.name
      %td= registration_work.nominate
      %td= registration_work.picture
      %td= registration_work.description
      %td= registration_work.supervizor
      %td= registration_work.partners
      %td= registration_work.city
      %td= registration_work.school
      %td= registration_work.area
      %td= registration_work.name_class
      %td= registration_work.url_work
      %td= registration_work.email
      %td= registration_work.phone
      %td= link_to 'Show', registration_work
      %td= link_to 'Edit', edit_registration_work_path(registration_work)
      %td= link_to 'Destroy', registration_work, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Registration work', new_registration_work_path

app/views/registration_works/new.html.haml
%h1 New registration_work

= render 'form'

= link_to 'Back', registration_works_path

app/views/registration_works/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @registration_work.name
%p
  %b Nominate:
  = @registration_work.nominate
%p
  %b Picture:
  = @registration_work.picture
%p
  %b Description:
  = @registration_work.description
%p
  %b Supervizor:
  = @registration_work.supervizor
%p
  %b Partners:
  = @registration_work.partners
%p
  %b City:
  = @registration_work.city
%p
  %b School:
  = @registration_work.school
%p
  %b Area:
  = @registration_work.area
%p
  %b Class:
  = @registration_work.name_class
%p
  %b Url work:
  = @registration_work.url_work
%p
  %b Email:
  = @registration_work.email
%p
  %b Phone:
  = @registration_work.phone

= link_to 'Edit', edit_registration_work_path(@registration_work)
\|
= link_to 'Back', registration_works_path