config/routes.rb
Masterit::Application.routes.draw do


  devise_scope :expert do
    post "users/omniauth_callbacks", to: "users/omniauth_callbacks#registration"
  end

  devise_scope :participant do
    post "users/omniauth_callbacks", to: "users/omniauth_callbacks#registration"
  end

  devise_scope :moderator do
    post "users/omniauth_callbacks", to: "users/omniauth_callbacks#registration"
  end

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => 'users/registrations' }

  devise_scope :admin do
    post "users/omniauth_callbacks", :to => "users/omniauth_callbacks#registration"
  end

  mount RailsAdmin::Engine => '/admin/rails_admin', :as => 'rails_admin'

  #root :to => "web/welcome#index"

  scope :module => :web do
    root :to => 'welcome#index'

    namespace :expert do
      root to: "welcome#index"
      resources :works, only: [:index, :show] do
        member do
          put :remove_from_basket
          put :trigger_estimate
        end
      end
      resources :estimations, only: [:edit, :update]
      resources :work_nominations, only: [:index]
    end
    namespace :moderator do
      root to: "welcome#index"
      resources :works, only: [:index, :show] do
        member do
          put :trigger_plagiat
        end
      end
      resources :users, only: [:index]
      resources :plagiat_details, only: [:index]
      resources :experts, only: [:index, :show] do
        scope module: :experts do
          resources :works, only: [:index, :show] do
            member do
              put :set_works_to_expert
              put :remove_works_from_expert
            end
          end
          resources :nominations, only: [:index, :show] do
            member do
              put :set_nomination_to_expert
              put :remove_nomination_from_expert
            end
          end
        end
      end
    end

    namespace :admin do
      root to: "welcome#index"
      resources :work_nominations
      resources :works
      resources :regions
      resources :competitions
      resources :tours
      resources :users, only: [:index, :edit, :update]
      resources :moderators, only: [:index, :show]
      resources :experts, only: [:index, :show] do
        scope module: :experts do
          resources :works, only: [:index, :show] do
            member do
              put :set_works_to_expert
              put :remove_works_from_expert
            end
          end
          resources :nominations, only: [:index, :show] do
            member do
              put :set_nomination_to_expert
              put :remove_nomination_from_expert
            end
          end
        end
      end
      resources :moderators, only: [:index, :show] do
        scope module: :moderators do
          resources :regions, only: [:index, :show] do
            member do
              put :set_region_to_moderator
              put :remove_region_from_moderator
            end
          end
        end
      end
      resource :expert do 
        member do
          put :send_invite_to_expert
        end
      end
      resource :moderator do 
        member do
          put :send_invite_to_moderator
        end
      end
      resource :user, only: [] do
        member do
          put :invite_to_expert
          put :invite_to_moderator
        end
      end
      resources :menu_items do
        scope module: :menu_items do
          resources :pages
        end
      end
    end

    resources :competitions, only: [:index, :show] do
      scope module: :competitions do
        resources :work_nominations, only: [:index, :show] do
          resource :plagiat_details, only: [:destroy, :new, :create, :edit, :update]
        end
      end
    end
    resources :pages, only: [:show]
    resources :users, only: [:show, :edit, :update]
    resources :works
    resources :comments
  end
end

app/views/layouts/web/shared/_ace_settings_container.html.haml
#ace-settings-container
  #ace-settings-btn.btn.btn-app.btn-mini.btn-warning
    %i.icon-cog
  #ace-settings-box
    %div
      %input#ace-settings-header.ace-checkbox-2{:type => "checkbox"}/
      %label.lbl{:for => "ace-settings-header"} Fixed Header
    %div
      %input#ace-settings-sidebar.ace-checkbox-2{:type => "checkbox"}/
      %label.lbl{:for => "ace-settings-sidebar"} Fixed Sidebar

app/views/layouts/web/shared/_application_signed_in.html.haml
%body
  .navbar.navbar-inverse
    .navbar-inner
      .container-fluid
        %a.brand{:href => "#"}
          %small
            %i.icon-leaf
            Мастер IT
        %ul.nav.ace-nav.pull-right
          - if user_signed_in?
            - if current_user.role? :admin
              %li.green
                %a.user-menu.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  %i.icon-tasks
                  %span Администратор
                  %i.icon-caret-down
                %ul#user_menu.pull-right.dropdown-menu.dropdown-yellow.dropdown-caret.dropdown-closer
                  %li= link_to "Управление данными", rails_admin_path
                  %li= link_to "Админка", admin_root_path
            - if current_user.role? :expert
              %li.purple
                %a.user-menu.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  %i.icon-tasks
                  %span Эксперт
                  %i.icon-caret-down
                %ul#user_menu.pull-right.dropdown-menu.dropdown-yellow.dropdown-caret.dropdown-closer
                  %li= link_to "Оценка работ", expert_root_path
            - if current_user.role? :moderator
              %li.red
                %a.user-menu.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  %i.icon-tasks
                  %span Модератор
                  %i.icon-caret-down
                %ul#user_menu.pull-right.dropdown-menu.dropdown-yellow.dropdown-caret.dropdown-closer
                  %li= link_to "Управление районом", moderator_root_path
            -if Competition.current.first.present? && Competition.current.first.started?
              %li.grey
                %a.user-menu.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  %i.icon-tasks
                  %span= t('.catalog_works')
                  %i.icon-caret-down
                %ul#user_menu.pull-right.dropdown-menu.dropdown-yellow.dropdown-caret.dropdown-closer
                  - Competition.all.each do |c|
                    = item :li, c, competition_work_nominations_path(c)
            %li.light-blue.user-profile
              %a.user-menu.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %span
                  = current_user.email
                %i.icon-caret-down
              %ul#user_menu.pull-right.dropdown-menu.dropdown-yellow.dropdown-caret.dropdown-closer
                %li
                  = link_to user_path(current_user) do
                    %i.icon-user
                    Аккаунт
                %li.divider
                %li
                  = link_to destroy_user_session_path, :method => :delete do
                    %i.icon-off
                    Выход
          - else
            %li.light-blue.user-profile
              = link_to "Войти", new_user_session_path
  #main-container.container-fluid
    %a#menu-toggler{:href => "#"}
      %span
    #sidebar
      %ul.nav.nav-list
        - nav_menu_items_arrange.each_pair do |menu_item, children|
          - if children.any?
            %li
              %a.dropdown-toggle{:href => "#"}
                %i.icon-file
                %span= menu_item.title
                %b.arrow.icon-angle-down
            %ul.submenu
              - children.each_key do |sub_item|
                %li
                  = link_to page_path(sub_item.pages.first) do
                    %i.icon-double-angle-right
                    %span= sub_item.title
          - else
            %li
              = link_to page_path(menu_item.pages.first) do
                %i.icon-desktop
                %span= menu_item.title
      / /.nav-list
      #sidebar-collapse
        %i.icon-double-angle-left
    #main-content.clearfix
      #page-content.clearfix
        - if content_for? (:header)
          .page-header.position-relative
            %h1
              = yield(:header)
        .row-fluid
          = bootstrap_flash
          .space-6

          = yield
      = render "layouts/web/shared/ace_settings_container"
  = render 'layouts/web/shared/footer'

app/views/layouts/web/shared/_application_signed_out.html.haml
%body.login-layout
  #main-container.container-fluid
    #main-content
      .row-fluid
        .span12
          .login-container
            .row-fluid
              .center
                %h1
                  %i.icon-leaf.green
                  %span.red Master
                  %span.white It
            .space-6
            .row-fluid
              .position-relative
                #login-box.visible.widget-box.no-border
                  .widget-body
                    .widget-main
                      = yield

app/views/layouts/web/shared/_breadcrumb.html.haml
#breadcrumbs
  %ul.breadcrumb
    %li
      %i.icon-home
      %a{:href => "#"} Home
      %span.divider
        %i.icon-angle-right
    %li.active Dashboard
  #nav-search
    %form.form-search
      %span.input-icon
        %input#nav-search-input.input-small.search-query{:autocomplete => "off", :placeholder => "Search ...", :type => "text"}/
        %i#nav-search-icon.icon-search

app/views/layouts/web/shared/_footer.html.haml
%a#btn-scroll-up.btn.btn-small.btn-inverse{:href => "#"}
  %i.icon-double-angle-up.icon-only.bigger-110
= render 'layouts/web/shared/javascripts'

app/views/layouts/web/shared/_head.html.haml
%head
  %meta(charset="utf-8")
  %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
  %meta(name="viewport" content="width=device-width, initial-scale=1.0")
  %title= content_for?(:title) ? yield(:title) : "Masterit"
  = csrf_meta_tags
  / Le HTML5 shim, for IE6-8 support of HTML elements
  /[if lt IE 9]
  = render "layouts/web/shared/stylesheets"
  %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
  %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
  %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
  %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
  %link(href="favicon.ico" rel="shortcut icon")

app/views/layouts/web/shared/_javascripts.html.haml
= javascript_include_tag "application"
= javascript_include_tag "bootstrap.min"
= javascript_include_tag "ace-elements.min"
= javascript_include_tag "ace.min"

app/views/layouts/web/shared/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand(href=root_path)= t(".logo_title")
      .container.nav-collapse
        %ul.nav

app/views/layouts/web/shared/_partners.html.haml
%hr
  %h3= t '.partners'
  .row
    - Partner.scoped.each do |partner|
      .span2
        = image_tag partner.image

app/views/layouts/web/shared/_sidebar_shortcuts.html.haml
#sidebar-shortcuts
  #sidebar-shortcuts-large
    %button.btn.btn-small.btn-success
      %i.icon-signal
    %button.btn.btn-small.btn-info
      %i.icon-pencil
    %button.btn.btn-small.btn-warning
      %i.icon-group
    %button.btn.btn-small.btn-danger
      %i.icon-cogs
  #sidebar-shortcuts-mini
    %span.btn.btn-success
    %span.btn.btn-info
    %span.btn.btn-warning
    %span.btn.btn-danger
/ #sidebar-shortcuts

app/views/layouts/web/shared/_stylesheets.html.haml
= stylesheet_link_tag "bootstrap"
= stylesheet_link_tag "bootstrap-responsive.min"
%link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,300", :rel => "stylesheet"}/
= stylesheet_link_tag "ace"
= stylesheet_link_tag "ace-responsive.min"
= stylesheet_link_tag "application"