config/routes.rb
Masterit::Application.routes.draw do


  devise_scope :expert do
    post "users/omniauth_callbacks", to: "users/omniauth_callbacks#registration"
  end

  devise_scope :participant do
    post "users/omniauth_callbacks", to: "users/omniauth_callbacks#registration"
  end

  devise_scope :moderator do
    post "users/omniauth_callbacks", to: "users/omniauth_callbacks#registration"
  end

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => 'users/registrations' }

  devise_scope :admin do
    post "users/omniauth_callbacks", :to => "users/omniauth_callbacks#registration"
  end

  mount RailsAdmin::Engine => '/admin/rails_admin', :as => 'rails_admin'

  #root :to => "web/welcome#index"

  scope :module => :web do
    root :to => 'welcome#index'

    namespace :expert do
      root to: "welcome#index"
      resources :works, only: [:index, :show] do
        member do
          put :remove_from_basket
          put :trigger_estimate
        end
      end
      resources :estimations, only: [:edit, :update]
      resources :work_nominations, only: [:index]
    end
    namespace :moderator do
      root to: "welcome#index"
      resources :works, only: [:index, :show] do
        member do
          put :trigger_plagiat
        end
      end
      resources :users, only: [:index]
      resources :plagiat_details, only: [:index]
      resources :experts, only: [:index, :show] do
        scope module: :experts do
          resources :works, only: [:index, :show] do
            member do
              put :set_works_to_expert
              put :remove_works_from_expert
            end
          end
          resources :nominations, only: [:index, :show] do
            member do
              put :set_nomination_to_expert
              put :remove_nomination_from_expert
            end
          end
        end
      end
    end

    namespace :admin do
      root to: "welcome#index"
      resources :work_nominations
      resources :works
      resources :regions
      resources :competitions
      resources :tours
      resources :users, only: [:index, :edit, :update]
      resources :moderators, only: [:index, :show]
      resources :experts, only: [:index, :show] do
        scope module: :experts do
          resources :works, only: [:index, :show] do
            member do
              put :set_works_to_expert
              put :remove_works_from_expert
            end
          end
          resources :nominations, only: [:index, :show] do
            member do
              put :set_nomination_to_expert
              put :remove_nomination_from_expert
            end
          end
        end
      end
      resources :moderators, only: [:index, :show] do
        scope module: :moderators do
          resources :regions, only: [:index, :show] do
            member do
              put :set_region_to_moderator
              put :remove_region_from_moderator
            end
          end
        end
      end
      resource :expert do 
        member do
          put :send_invite_to_expert
        end
      end
      resource :moderator do 
        member do
          put :send_invite_to_moderator
        end
      end
      resource :user, only: [] do
        member do
          put :invite_to_expert
          put :invite_to_moderator
        end
      end
      resources :menu_items do
        scope module: :menu_items do
          resources :pages
        end
      end
    end

    resources :competitions, only: [:index, :show] do
      scope module: :competitions do
        resources :work_nominations, only: [:index, :show] do
          resource :plagiat_details, only: [:destroy, :new, :create, :edit, :update]
        end
      end
    end
    resources :pages, only: [:show]
    resources :users, only: [:show, :edit, :update]
    resources :works
    resources :comments
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :authorizations, :dependent => :destroy
  has_many :works
  has_many :posts
  has_many :plagiat_details
  has_many :works, through: :plagiat_details
  
  acts_as_inkwell_user

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :type, :first_name,
                  :last_name, :patronymic

  ROLES = %w[User Expert Moderator Admin]

  def role?(_type)
    type == _type.to_s.capitalize
  end

  def can_ban?(work)
    if plagiat_details.empty? 
      return true
    end
    plagiat_details.where("work_id = ?", work.id) == nil
  end
  def expert?
    type == :Expert
  end

  def role
    return :user if type.nil?
    type.downcase
  end

  def has_privileges?
    return role?(:admin) || role?(:moderator)
  end

  def to_s
    [last_name, first_name].compact.join(" ")
  end

  def to_s
    "#{last_name} #{first_name}"
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorize
  end

  def vkontakte
    authorize
  end

  def google_oauth2
    authorize
  end

  def twitter 
    authorize
  end

  def registration
    email = params[:user][:email]
    
    if User.find_by_email email
      flash_notice
    else
      @user = User.new
      @user = get_user_by_populator(@user, auth_hash)
      @user.email = email
      @user.type = :User
      @user.authorizations << build_authorization(auth_hash)
      @user.type = "Participant"
      if @user.save
        sign_in @user
        flash_success
      else
        flash_error
      end

    end

    redirect_to root_path
  end

  def authorize
    save_omniauth_to_session

    authorization = Authorization.find_by_provider_and_uid(auth_hash[:provider], auth_hash[:uid].to_s)

    if !authorization && user_signed_in? 
      current_user.authorizations << build_authorization(auth_hash)      
      current_user.save
      flash_success
      redirect_to root_path
    elsif authorization
      sign_in authorization.user
      flash_success
      redirect_to root_path
    else
      @user = User.new
      render '/users/new'
    end  
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include TimepadHelper
  def create
    build_resource

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        
        UserMailer.welcome(resource).deliver
        add_to_timepad_maillist(resource)
        resource.type = "Participant"
        resource.save
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end 

app/controllers/web/admin/users_controller.rb
class Web::Admin::UsersController < Web::Admin::ApplicationController
  respond_to :html
  def index
    @q = User.ransack params[:q]
    @users = @q.result.page(params[:page])
    respond_with @users, location: admin_users_path
  end
  
  def invite_to_expert
    @user = User.find params[:participant][:id]
    @user.type = :expert.to_s.capitalize
    @user.save
    respond_with @users, location: admin_users_path
  end

  def invite_to_moderator
    @user = User.find params[:participant][:id]
    @user.type = :moderator.to_s.capitalize
    @user.save
    respond_with @users, location: admin_users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find params[:id]

    if @user.update_attributes params[:user]
      flash_success
      redirect_to edit_admin_user_path(@user)
    else
      flash_error
      render action: :edit
    end
  end
end

app/controllers/web/moderator/users_controller.rb
class Web::Moderator::UsersController < Web::Moderator::ApplicationController
  respond_to :html
  def index
    @q = User.ransack params[:q]
    @users = @q.result.page(params[:page])
    respond_with @users, location: moderator_users_path
  end
  
  def invite_to_expert
    @user = User.find params[:participant][:id]
    @user.type = :expert.to_s.capitalize
    @user.save
    respond_with @users, location: moderator_users_path
  end

end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ApplicationController
  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]

    if @user.update_attributes params[:user]
      redirect_to edit_user_path(@user)
    else
      render action: :edit
    end
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/web/admin/users/_form.html.haml
= simple_form_for @user, :url => url, :html => { :class => 'default_class' } do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :patronymic
  = f.input :email
  = f.input :password
  .form-actions
    = f.button :submit, :class => 'btn btn-primary'
    = link_to t('.cancel'), user_path(@user), :class => 'btn'

app/views/web/admin/users/edit.html.haml
%h3=t '.user_edit'
= render "form", url: user_path(@user)

app/views/web/admin/users/index.html.haml
= simple_form_for :q, url: admin_users_path, method: :get, html: {class: 'form-inline filters'} do |s|
  = s.input :type_eq, as: :chosen_select, collection: [["Админы", "Admin"], ["Эксперты", "Expert"], ["Участники", "Participant"], ["Модераторы", "Moderator"]], label: false,  include_blank: t('.choose')
  = s.button :submit, value: t('.find_users'),class: 'btn-primary'
%table.table.table-striped
  %thead
    %tr
      %th= sort_link @q, :id
      %th= sort_link @q, :first_name
      %th= sort_link @q, :last_name
      %th= sort_link @q, :email
      %th= sort_link @q, :role
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.first_name
        %td= user.last_name
        %td= user.email
        %td= t ".roles.#{user.role}"
        %td
          = link_to edit_admin_user_path(user), class: 'btn btn-mini' do
            %i.icon-pencil
          -if user.role? :participant
            = simple_form_for user, method: :put, url: invite_to_expert_admin_user_path do |f|
              = f.input :id, as: :hidden
              = button_tag(type: 'submit', title: t('.expert_invite'), class: "btn btn-mini") do
                %i.icon-hand-right
            = simple_form_for user, method: :put, url: invite_to_moderator_admin_user_path do |f|
              = f.input :id, as: :hidden
              = button_tag(type: 'submit', title: t('.moderator_invite'), class: "btn btn-mini") do
                %i.icon-user

app/views/web/admin/users/show.html.haml
.tabbable
  %ul.nav.nav-tabs
    %li.active= link_to t('.info'), '#info', data: { toggle: 'tab' }
    %li= link_to t('.my_works'), '#my_works', data: { toggle: 'tab' }
    %li= link_to t('.my_accounts'), '#my_accounts', data: { toggle: 'tab' }

  .tab-content
    .tab-pane.active#info
      %h3= t('.users')
      .row
        .span8
          = link_to t(".user_edit"), edit_user_path
          %br
          = link_to t(".registrate_work"), new_work_path
    .tab-pane#my_works
      -#= link_to t(".works"), works_path
    .tab-pane#my_accounts
      = link_to "Привязать facebook", user_omniauth_authorize_path(:facebook)
      %br
      = link_to "Привязать google", user_omniauth_authorize_path(:google_oauth2)
      %br
      = link_to "Привязать twitter", user_omniauth_authorize_path(:twitter)
      %br
      = link_to "Привязать vkontakte", user_omniauth_authorize_path(:vkontakte)