config/routes.rb
Masterit::Application.routes.draw do


  devise_scope :expert do
    post "users/omniauth_callbacks", to: "users/omniauth_callbacks#registration"
  end

  devise_scope :participant do
    post "users/omniauth_callbacks", to: "users/omniauth_callbacks#registration"
  end

  devise_scope :moderator do
    post "users/omniauth_callbacks", to: "users/omniauth_callbacks#registration"
  end

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => 'users/registrations' }

  devise_scope :admin do
    post "users/omniauth_callbacks", :to => "users/omniauth_callbacks#registration"
  end

  mount RailsAdmin::Engine => '/admin/rails_admin', :as => 'rails_admin'

  #root :to => "web/welcome#index"

  scope :module => :web do
    root :to => 'welcome#index'

    namespace :expert do
      root to: "welcome#index"
      resources :works, only: [:index, :show] do
        member do
          put :remove_from_basket
          put :trigger_estimate
        end
      end
      resources :estimations, only: [:edit, :update]
      resources :work_nominations, only: [:index]
    end
    namespace :moderator do
      root to: "welcome#index"
      resources :works, only: [:index, :show] do
        member do
          put :trigger_plagiat
        end
      end
      resources :users, only: [:index]
      resources :plagiat_details, only: [:index]
      resources :experts, only: [:index, :show] do
        scope module: :experts do
          resources :works, only: [:index, :show] do
            member do
              put :set_works_to_expert
              put :remove_works_from_expert
            end
          end
          resources :nominations, only: [:index, :show] do
            member do
              put :set_nomination_to_expert
              put :remove_nomination_from_expert
            end
          end
        end
      end
    end

    namespace :admin do
      root to: "welcome#index"
      resources :work_nominations
      resources :works
      resources :regions
      resources :competitions
      resources :tours
      resources :users, only: [:index, :edit, :update]
      resources :moderators, only: [:index, :show]
      resources :experts, only: [:index, :show] do
        scope module: :experts do
          resources :works, only: [:index, :show] do
            member do
              put :set_works_to_expert
              put :remove_works_from_expert
            end
          end
          resources :nominations, only: [:index, :show] do
            member do
              put :set_nomination_to_expert
              put :remove_nomination_from_expert
            end
          end
        end
      end
      resources :moderators, only: [:index, :show] do
        scope module: :moderators do
          resources :regions, only: [:index, :show] do
            member do
              put :set_region_to_moderator
              put :remove_region_from_moderator
            end
          end
        end
      end
      resource :expert do 
        member do
          put :send_invite_to_expert
        end
      end
      resource :moderator do 
        member do
          put :send_invite_to_moderator
        end
      end
      resource :user, only: [] do
        member do
          put :invite_to_expert
          put :invite_to_moderator
        end
      end
      resources :menu_items do
        scope module: :menu_items do
          resources :pages
        end
      end
    end

    resources :competitions, only: [:index, :show] do
      scope module: :competitions do
        resources :work_nominations, only: [:index, :show] do
          resource :plagiat_details, only: [:destroy, :new, :create, :edit, :update]
        end
      end
    end
    resources :pages, only: [:show]
    resources :users, only: [:show, :edit, :update]
    resources :works
    resources :comments
  end
end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :description, :image, :estimations, :name, :state_event, :work_nomination, :user_id, :tour_id, :region_id, :work_nomination_id

  belongs_to :user
  has_many :sources, :dependent => :destroy
  has_many :videos, :dependent => :destroy
  has_many :images, :dependent => :destroy
  has_many :estimations
  has_many :experts, through: :estimations
  has_many :plagiat_details
  has_many :users, through: :plagiat_details

  belongs_to :tour
  belongs_to :region
  belongs_to :work_nomination

  accepts_nested_attributes_for :sources, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :videos, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :images, :reject_if => :all_blank, :allow_destroy => true

  acts_as_inkwell_post

  state_machine :plagiat_state, initial: :passing, namespace: :plagiat_state do
    state :passing
    state :banned
    event :ban do
      transition all => :banned
    end
    event :originality_confirm do
      transition all => :passing
    end
  end
  state_machine :estimate_state, initial: :on_estimating, namespace: :estimate_state do
    state :estimated
    state :on_estimating
    event :estimate do
      transition :on_estimating => :estimated
    end
    event :prepare do
      transition :estimated => :on_estimating
    end
  end

  def to_s
    name
  end

end

app/controllers/web/admin/experts/works_controller.rb
class Web::Admin::Experts::WorksController < Web::Admin::Experts::ApplicationController
  def index
    @expert = User.find_by_id params[:expert_id]
    @q = Work.ransack params[:q]
    @works = @q.result.page(params[:page])
    respond_with @works, location: admin_expert_works_path
  end
  def show
    @work = Work.find_by_id params[:id]
    respond_with @work, location: admin_expert_work_path
  end
  def remove_works_from_expert
    @expert = User.find params[:expert_id]
    work = Work.find params[:id]
    @expert.basket.works.delete work
    @expert.save!
    respond_with @works, location: admin_expert_works_path
  end
  def set_works_to_expert
    @expert = User.find params[:expert_id]
    @expert.basket = Basket.new if @expert.basket.nil?
    work = Work.find params[:id]
    if (work.estimations.where("expert_id = ?", @expert.id).first.nil?)
      estimation = Estimation.new
      work.estimations << estimation
      work.save!
      @expert.estimations << estimation
    end
    @expert.basket.works << work
    @expert.save!
    respond_with @works, location: admin_expert_works_path
  end
end

app/controllers/web/admin/works_controller.rb
class Web::Admin::WorksController < Web::Admin::ApplicationController
  def index
    @q = WorkCreateType.ransack params[:q]
    @works = @q.result.page(params[:page])
  end
  
  def new
    @work = Work.new
  end
  
  def edit
    @work = WorkCreateType.find(params[:id])
  end
  
  def update
    @work = WorkCreateType.find params[:id]

    if @work.update_attributes params[:work]
      flash_success
      redirect_to admin_work_nominations_path
    else
      flash_error
      render action: :edit
    end
  end
    
  def create
    @work = WorkCreateType.new params[:work]
    if @work.save
      flash[:success] = flash_translate(:success)
      redirect_to user_path(current_user)
    else
      render :action => :new
    end
  end
  
  def destroy
    @work = Work.find params[:id]
    @work.destroy
    redirect_to admin_works_path
  end
end

app/controllers/web/expert/works_controller.rb
class Web::Expert::WorksController < Web::Expert::ApplicationController
  def index

    @works = current_user.basket.nil? ? [] : current_user.basket.works
    respond_with @works, location: expert_works_path
  end
  def show
    @work = Work.find_by_id params[:id]
    respond_with @work, location: expert_work_path
  end
  def trigger_estimate
    work = Work.find_by_id params[:id]
    if work.estimate_state_estimated?
      work.prepare_estimate_state
    else
      work.estimate_estimate_state
    end
    @works = current_user.basket.works
    respond_with @works, location: expert_works_path
  end
  def remove_from_basket
    @work = Work.find_by_id params[:id]
    current_user.basket.works.delete @work
    @works = current_user.basket.works
    respond_with @works, location: expert_works_path
  end
end

app/controllers/web/moderator/experts/works_controller.rb
class Web::Moderator::Experts::WorksController < Web::Moderator::Experts::ApplicationController
  def index
    @expert = User.find_by_id params[:expert_id]
    @q = Work.ransack params[:q]
    @works = @q.result.page(params[:page])
    respond_with @works, location: admin_expert_works_path
  end
  def show
    @work = Work.find_by_id params[:id]
    respond_with @work, location: admin_expert_work_path
  end
  def remove_works_from_expert
    @expert = User.find params[:expert_id]
    work = Work.find params[:id]
    @expert.basket.works.delete work
    @expert.save!
    respond_with @works, location: admin_expert_works_path
  end
  def set_works_to_expert
    @expert = User.find params[:expert_id]
    @expert.basket = Basket.new if @expert.basket.nil?
    work = Work.find params[:id]
    if (work.estimations.where("expert_id = ?", @expert.id).first.nil?)
      estimation = Estimation.new
      work.estimations << estimation
      @expert.estimations << estimation
    end
    work.save!
    @expert.basket.works << work
    @expert.save!
    respond_with @works, location: admin_expert_works_path
  end
end

app/controllers/web/moderator/works_controller.rb
class Web::Moderator::WorksController < Web::Moderator::ApplicationController
  def index
    id = -1;
    id = current_user.region.id if current_user.region.present?
    @q = Work.ransack params[:q] || {region_id_eq: id}
    @works = @q.result.page(params[:page])
  end
  def show
    @work = Work.find_by_id params[:id]
    respond_with @work, location: moderator_work_path
  end
  def trigger_plagiat
    work = Work.find_by_id params[:id]
    if work.plagiat_state_banned?
      work.originality_confirm_plagiat_state
    else
      work.ban_plagiat_state
    end
    @q = Work.ransack params[:q] || {region_id_eq: current_user.region.id}
    @works = @q.result.page(params[:page])
    respond_with @works, location: moderator_works_path
  end
end

app/controllers/web/works_controller.rb
class Web::WorksController < Web::ApplicationController
  def new
    @work = Work.new
  end
  def create
    @work = WorkCreateType.new params[:work]
    if @work.save
      flash[:success] = flash_translate(:success)
      redirect_to user_path(current_user)
    else
      render :action => :new
    end
  end

  def index
    @works = Work.scoped
  end

  def show
    @work = Work.find params[:id]
    @comments = @work.commentline
    @new_comment = Inkwell::Comment.new
  end
end

app/views/web/admin/works/_form.html.haml
= simple_form_for @work, :url => url, :html => {:class => "form-horizontal"}do |f|
  = f.input :name
  = f.input :image
  = f.input :description, as: :string
  = f.association :tour
  = f.association :region
  = f.association :work_nomination
  = f.input :user_id, as: :hidden, input_html: { value:  current_user.id }
  %hr
  = f.simple_fields_for :sources do |u|
    = render 'source_fields', :f => u
  .links.control-group
    = link_to_add_association t('add_source'), f, :sources

  = f.simple_fields_for :videos do |u|
    = render 'video_fields', :f => u
  .links.control-group
    = link_to_add_association t('add_video'), f, :videos

  = f.simple_fields_for :images do |u|
    = render 'image_fields', :f => u
  .links.control-group
    = link_to_add_association t('add_image'), f, :images

  .form-actions
    = f.button :submit

app/views/web/admin/works/_image_fields.html.haml
.control-group.nested-fields
  = link_to_remove_association f, class: 'close' do
    %i.icon-trash
  = f.input :name
  = f.input :url
  = f.input :description, as: :string

app/views/web/admin/works/_source_fields.html.haml
.control-group.nested-fields
  = link_to_remove_association f, class: 'close' do
    %i.icon-trash
  = f.input :name
  = f.input :url
  = f.input :description, as: :string

app/views/web/admin/works/_video_fields.html.haml
.control-group.nested-fields
  = link_to_remove_association f, class: 'close' do
    %i.icon-trash
  = f.input :name
  = f.input :url
  = f.input :description, as: :string

app/views/web/admin/works/edit.html.haml
= render "form", url: admin_work_path(@work)

app/views/web/admin/works/index.html.haml
= link_to t('.new'), new_admin_work_path, :class => 'btn btn-primary'

%table.table.table-striped
  %thead
    %tr
      %th= sort_link @q, :id
      %th= sort_link @q, :name
      %th= sort_link @q, :image
      %th= sort_link @q, :tour_id
      %th= sort_link @q, :region_id
      -#%th= sort_link @q, :nominate
      -#%th= sort_link @q, :state
      %th= sort_link @q, :user_id
      %th
  %tbody
    - @works.each do |item|
      %tr
        %td= item.id
        %td= item.name
        %td= item.image
        %td= item.tour
        %td= item.region
        -#%td= item.nominate
        -#%td= item.human_state_name
        %td= User.find(item.user_id)
        %td
          .pull-right.btn-group
            = link_to edit_admin_work_path(item), :class => 'btn btn-mini' do
              %i.icon-pencil
            = link_to admin_work_path(item), :method => :delete, :data => { :confirm => t('.confirm') }, :class => 'btn btn-mini btn-danger' do
              %i.icon-trash

= paginate @works

app/views/web/admin/works/new.html.haml
= render "form", url: admin_works_path